<a href="https://colab.research.google.com/github/abhinavpanuganti69/MOVIE-RECOMMENDATION-SYSTEM/blob/main/MOVIE_RECOMMENDATION_SYSTEM_ABHINAV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


DATA COLLECTION AND PRE_PROCESSING

In [56]:
# Loading the data from the csv file to a pandas dataframe
movies_data = pd.read_csv('/content/TeluguMovies_dataset.csv')

In [57]:
# Printing the first 5 rows of the dataframe
movies_data.head()

Unnamed: 0                        Movie    Year Certificate  \
0           0      Bahubali: The Beginning  2015.0          UA   
1           1  Baahubali 2: The Conclusion  2017.0          UA   
2           2              1 - Nenokkadine  2014.0          UA   
3           3                      Dhoom:3  2013.0          UA   
4           4                       Ra.One  2011.0           U   

                                   Genre  \
0              Action, Drama               
1              Action, Drama               
2           Action, Thriller               
3           Action, Thriller               
4  Action, Adventure, Sci-Fi               

                                            Overview  Runtime  Rating  \
0      In ancient India, an adventurous and darin...      159     8.1   
1      When Shiva, the son of Bahubali, learns ab...      167     8.2   
2      A rock star must overcome his psychologica...      170     8.1   
3      When Sahir, a circus entertainer trained i...      172     5.4   
4      When the titular antagonist of an action g...      156     4.6   

   No.of.Ratings  
0          99114  
1          71458  
2          42372  
3          42112  
4          37211

In [58]:
#number of rows and columns in the dataset
movies_data.shape

(1400, 9)

In [61]:
# selecting the relevant features for recommendation
selected_features = ['Genre','Overview','Movie','Rating']
print(selected_features)


['Genre', 'Overview', 'Movie', 'Rating']


In [69]:
# Replacing the null values with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [71]:
#Combining all the 4 selected features
combined_features = movies_data['Genre'].astype(str) +' '+movies_data['Overview'].astype(str) +' '+movies_data['Movie'].astype(str) +' '+movies_data['Rating'].astype(str)

In [72]:
print(combined_features)

0       Action, Drama                 In ancient India...
1       Action, Drama                 When Shiva, the ...
2       Action, Thriller                 A rock star m...
3       Action, Thriller                 When Sahir, a...
4       Action, Adventure, Sci-Fi                 When...
                              ...                        
1395                                    Maro Monagadu 8.6
1396    Comedy, Drama                 The movie is abo...
1397    Drama, Romance                 Muvva Gopaludu ...
1398         Hero Charan (Tarun) a middle class family...
1399    Drama                 Surendra marries Savitri...
Length: 1400, dtype: object


In [76]:
# Converting the text data to feature vectors(numerical Values)
vectorizer = TfidfVectorizer()


In [77]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [78]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32435 stored elements and shape (1400, 6702)>
  Coords	Values
  (0, 159)	0.07411837375549563
  (0, 1734)	0.06926665194621266
  (0, 2690)	0.15834279963742298
  (0, 352)	0.2745537850890944
  (0, 2703)	0.1818411048739418
  (0, 339)	0.1064045129508743
  (0, 214)	0.2837866798340414
  (0, 353)	0.07208409715812306
  (0, 1447)	0.3124666704641771
  (0, 3479)	0.12913506667402888
  (0, 696)	0.1977467079436342
  (0, 2799)	0.23195175760409958
  (0, 1485)	0.2745537850890944
  (0, 4095)	0.21325020405606415
  (0, 2067)	0.2606317482342353
  (0, 740)	0.17609654145477932
  (0, 6169)	0.15781505730416462
  (0, 6534)	0.2837866798340414
  (0, 4319)	0.1928732604944429
  (0, 628)	0.29568995142451354
  (0, 5961)	0.06646609204545577
  (0, 704)	0.3124666704641771
  (1, 159)	0.06275125452625636
  (1, 1734)	0.058643614076005254
  (1, 2690)	0.06702932632619459
  :	:
  (1399, 4069)	0.05461860016493604
  (1399, 6043)	0.14848008666732085
  (1399, 6604)	0.073

COSINE SIMILARITY

In [79]:
#getting the similarity score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [80]:
print(similarity)

[[1.         0.10457084 0.00618659 ... 0.02674187 0.01652326 0.04053726]
 [0.10457084 1.         0.04961868 ... 0.03508289 0.07909854 0.05722518]
 [0.00618659 0.04961868 1.         ... 0.         0.03889234 0.01153394]
 ...
 [0.02674187 0.03508289 0.         ... 1.         0.04434499 0.01276055]
 [0.01652326 0.07909854 0.03889234 ... 0.04434499 1.         0.02776065]
 [0.04053726 0.05722518 0.01153394 ... 0.01276055 0.02776065 1.        ]]


In [81]:
print(similarity.shape)

(1400, 1400)


In [91]:
# getting the movie name by the user
movie_name = input('Enter the Movie Name:')

Enter the Movie Name:Eega


In [92]:
#creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['Movie'].tolist()
print(list_of_all_titles)

['Bahubali: The Beginning', 'Baahubali 2: The Conclusion', '1 - Nenokkadine', 'Dhoom:3', 'Ra.One', 'Dhoom:2', 'Eega', 'Krrish 3', 'Arjun Reddy', 'Rangasthalam', 'Magadheera', 'War', 'Bharat Ane Nenu', 'Saaho', 'Theri', 'Dookudu', 'Pokiri', 'Sarkar', 'Athadu', 'The Ghazi Attack', 'Kabali', 'MSG: The Messenger of God', 'Nanban', 'Srimanthudu', 'Veer - Vivegam', 'Billa 2', 'Manam', '7 Aum Arivu', 'Bigil', 'Business Man', 'Geetha Govindam', 'Mahanati', 'Spyder', 'Nannaku Prematho', 'Dabangg 3', 'MSG 2 the Messenger', 'Manikarnika: The Queen of Jhansi', 'Race Gurram', 'Okkadu', 'Bommarillu', 'Atharintiki Daaredi', 'Khaleja', 'Yennai Arindhaal', 'Thalaivaa', 'Kaala', 'Bairavaa', 'Goodachari', 'Puli', 'Pulimurugan', 'Veeram', 'Vedam', 'Yevadu', 'Aravindha Sametha Veera Raghava', 'Billa', 'Jersey', 'Sye Raa Narasimha Reddy', 'Ala Vaikunthapurramuloo', 'Janatha Garage', 'Gabbar Singh', 'Temper', 'Game Over', 'Singam 2', 'Dhruva', 'Jalsa', 'Maharshi', 'Pelli Choopulu', 'Arya 2', 'Chekka Chivanth

In [93]:
#finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Eega']


In [94]:
close_match = find_close_match[0]
print(close_match)

Eega


In [100]:
# Find the index of the movie with title
index_of_the_movie = movies_data[movies_data['Movie'] == close_match].index[0]
print(index_of_the_movie)

6


In [101]:
#getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)


[(0, np.float64(0.035349506927619616)), (1, np.float64(0.033726080776540664)), (2, np.float64(0.08772004218558258)), (3, np.float64(0.0323284212562278)), (4, np.float64(0.01949194954718523)), (5, np.float64(0.027908513436920423)), (6, np.float64(1.0000000000000002)), (7, np.float64(0.05834226596181804)), (8, np.float64(0.03902149351046401)), (9, np.float64(0.0586257858389587)), (10, np.float64(0.08642293455451447)), (11, np.float64(0.018177036139082774)), (12, np.float64(0.01211187568229877)), (13, np.float64(0.018124789346480312)), (14, np.float64(0.03416252318500911)), (15, np.float64(0.02824986590926317)), (16, np.float64(0.022885230035689777)), (17, np.float64(0.025203604554143007)), (18, np.float64(0.047229450516525585)), (19, np.float64(0.014138232846559611)), (20, np.float64(0.023019874777592826)), (21, np.float64(0.02049561081821918)), (22, np.float64(0.006023598812045)), (23, np.float64(0.030798644850005896)), (24, np.float64(0.02195912936184539)), (25, np.float64(0.0147688949

In [102]:
len(similarity_score)

1400

In [103]:
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse=True)
print(sorted_similar_movies)

[(6, np.float64(1.0000000000000002)), (552, np.float64(0.3088982453039397)), (628, np.float64(0.30310224460211765)), (688, np.float64(0.2342228163702276)), (1196, np.float64(0.20914080748900538)), (826, np.float64(0.18463695852338333)), (515, np.float64(0.17645410636565156)), (28, np.float64(0.14712223541114333)), (199, np.float64(0.14583900526929694)), (238, np.float64(0.1431845310681621)), (790, np.float64(0.14154405545597354)), (222, np.float64(0.14104075634065708)), (558, np.float64(0.1406453946119288)), (140, np.float64(0.13872547649937927)), (483, np.float64(0.13716752728228368)), (51, np.float64(0.12927758187710525)), (726, np.float64(0.12740347533175667)), (449, np.float64(0.12576768782080652)), (319, np.float64(0.11875911577331023)), (697, np.float64(0.11555055452959187)), (298, np.float64(0.11434011994191767)), (898, np.float64(0.11113003433047455)), (576, np.float64(0.11062252224468037)), (93, np.float64(0.11051449534864605)), (657, np.float64(0.11027973417948717)), (402, np

In [105]:
#print the name of similar movies based on the index
print('Movies Suggested for You: \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['Movie'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1

Movies Suggested for You: 

1 . Eega
2 . Veera
3 . Shadow
4 . Yamudiki Mogudu
5 . Nagarahaavu
6 . Padmavyuham
7 . Yaman
8 . Bigil
9 . Ramayya Vastavayya
10 . Rebel
11 . Bezawada
12 . Nijam
13 . Mesthri
14 . Agnyaathavaasi
15 . Samba
16 . Yevadu
17 . Yamaleela
18 . Yamajaathakudu
19 . Uu Kodathara Ulikki Padathara
20 . Jaguar
21 . Rakhi
22 . Poola Rangadu
23 . Allari Police
24 . Rakhta Charitra
25 . Winner
26 . Krishnam Vande Jagadgurum
27 . Yamadonga
28 . Run Raja Run
29 . Rakhta Charitra 2


MOVIE RECOMMENDATION SYSTEM

In [113]:
movie_name = input('Enter the Movie Name:')
list_of_all_titles = movies_data['Movie'].tolist()
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data['Movie'] == close_match].index[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse=True)
print('Movies Suggested for You: \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['Movie'].values[0]
  if (i<11):
    print(i,'.',title_from_index)
    i+=1

Enter the Movie Name:avatar
Movies Suggested for You: 

1 . Savaari
2 . Mrugaraaju
3 . Sitaara
4 . Malliswari
5 . Lakshmi Raave Maa Intiki
6 . Prayanam
7 . Chi La Sow
8 . Gundamma Katha
9 . Padmavyuham
10 . Rough


In [117]:
import gradio as gr
import difflib

def recommend_ui(movie_name):
    list_of_all_titles = movies_data['Movie'].tolist()
    find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

    if not find_close_match:
        return "❌ No similar movie found. Please check the spelling."

    close_match = find_close_match[0]
    index_of_the_movie = movies_data[movies_data['Movie'] == close_match].index[0]
    similarity_score = list(enumerate(similarity[index_of_the_movie]))
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    result = f"🎬 Movies Suggested for You (Based on '{close_match}'):\n\n"
    i = 1
    for movie in sorted_similar_movies:
        index = movie[0]
        title_from_index = movies_data[movies_data.index == index]['Movie'].values[0]
        if i < 11:
            result += f"{i}. {title_from_index}\n"
            i += 1

    return result


In [120]:
interface = gr.Interface(
    fn=recommend_ui,
    inputs=gr.Textbox(lines=1, placeholder="Meeku nacchina telugu Movies..."),
    outputs="textbox",
    title="🎥 Movie Recommendation System - Abhinav Panuganti",
    description="Type any movie name and get similar movies based on content matching.",
)

interface.launch()


It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://c01e08195a0a67de59.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
